// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_c5akEieyvHdAS0rDVKmmB4D1jSAdvk',
    appId: '1:446207384356:web:cb8e660a6c39035fe971b1',
    messagingSenderId: '446207384356',
    projectId: 'sheltr-fea25',
    authDomain: 'sheltr-fea25.firebaseapp.com',
    storageBucket: 'sheltr-fea25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5oDg-hMxDIafS2-LjSYpOiOprC0aNfs',
    appId: '1:446207384356:android:a1893db291e9921be971b1',
    messagingSenderId: '446207384356',
    projectId: 'sheltr-fea25',
    storageBucket: 'sheltr-fea25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATV8jKOuwB-C01RRoVX39Mwy0xyEApuuY',
    appId: '1:446207384356:ios:cd4d9f3139fd8813e971b1',
    messagingSenderId: '446207384356',
    projectId: 'sheltr-fea25',
    storageBucket: 'sheltr-fea25.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATV8jKOuwB-C01RRoVX39Mwy0xyEApuuY',
    appId: '1:446207384356:ios:cd4d9f3139fd8813e971b1',
    messagingSenderId: '446207384356',
    projectId: 'sheltr-fea25',
    storageBucket: 'sheltr-fea25.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
